spring:
  application:
    name: oauth-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.27.220.53:3306/blog?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true
  redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: 123456
      timeout: 3600
      jedis:
            pool:
              max-active: 8
              max-wait: -1s
              min-idle: 0
              max-idle: 8
logging:
  level:
    web: info
    com:
      oauth:
        mapper: debug
    org:
      springfromework:
        security: info
imooc:
  security:
    browser:
     # loginPage: /demo-signIn.html
     # loginType: REDIRECT
      loginType: JSON
    code:
      image:
        width: 100
        height: 50
        url: /order,/user/*
server:
  port: 8088
