logging:
  level:
    com:
        oauth:
            mapper: debug
    web: debug
mybatis:
    mapper-locations: classpath:mappers/*.xml
server:
    port: 8098
spring:
  application:
      name: oauth-service
  datasource:
      driverclassname: com.mysql.jdbc.Driver
      password: 123456
      url: jdbc:mysql://120.27.220.53:3306/blog_security?useunicode=true&characterencoding=utf8
      username: root
  main:
      allow-bean-definition-overriding: true
eureka:
  client:
      serviceUrl:
        defaultZone: http://localhost:8093/eureka/